name: Generate Snake Animation

on:
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate snake.svg with dynamic colors
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=github-light&dynamic=true

      - name: Add custom animation and style to snake.svg
        run: |
          # You can run a script to edit or add custom styles/animations to the generated SVG
          # Change the colors based on the theme
          sed -i 's/#000000/#3498db/g' dist/snake.svg # Example: Change color to blue for light theme
          sed -i 's/#ffffff/#2c3e50/g' dist/snake.svg # Dark background

          sed -i '/<svg>/a <style> .snake { animation: moveSnake 5s ease-in-out infinite; } @keyframes moveSnake { 0% { transform: translateX(0); opacity: 1; } 50% { transform: translateX(50%); opacity: 0.5; } 100% { transform: translateX(100%); opacity: 1; } } </style>' dist/snake.svg

          sed -i '/<svg>/a <style> .snake { filter: brightness(1.2); } </style>' dist/snake.svg

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
