name: Generate Snake Animation

on:
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Detect system theme and generate snake.svg
        id: generate_snake
        run: |
          THEME="light"
          if [ "${{ github.event.head_commit.committer.name }}" == "github-actions" ]; then
            THEME="dark"
          fi
          if [ "$THEME" == "dark" ]; then
            PALETTE="github-dark"
          else
            PALETTE="github-light"
          fi
          echo "Using theme: $THEME"
          curl -L "https://raw.githubusercontent.com/Platane/snk/svg-only/v3/snk?palette=$PALETTE&github_user_name=${{ github.repository_owner }}" -o dist/snake.svg

      - name: Add custom animation and style to snake.svg
        run: |
          sed -i 's/#000000/#3498db/g' dist/snake.svg
          sed -i '/<svg>/a <style> .snake { animation: moveSnake 8s ease-in-out infinite; } @keyframes moveSnake { 0% { transform: translateX(0); } 50% { transform: translateX(50%); } 100% { transform: translateX(100%); } } </style>' dist/snake.svg
          sed -i 's/#ffffff/#f39c12/g' dist/snake.svg

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
